### PR TITLE
Features - Create navbar, create popup, create button components

### PR DESCRIPTION
**Pull request by jlu9d2**
created navbar
-added local state for zip code input, category input (for testing)
-added logo
-added navbar component

-added category component
-added zipcode input component
-added search button component
-added popup component

styling applied based on variant(popup and navbar)

Screenshot 2023-01-22 at 11 13 25 AM
Screenshot 2023-01-22 at 4 35 21 PM

### CODE REVIEW

**Review by jiyunnoh — COMMENTED** [review]
Need to break down into <SearchForm>, <Button> components.

**Review by AaronoKwok — APPROVED** [review]
Looks great!

**Comment by jlu9d2** [comment]
> Need to break down into 'SearchForm', 'Button' components. Please check out #31, #21 and #45.

added button component

**Comment by jlu9d2** [comment]
added button component, popup component, button component, zipcode input component, category component (saved to this branch)

**Review by jiyunnoh — APPROVED** [review]

**Pull request merged**
